/**
 * HAP's Coding Snacks Recommendation Data
 *
 * What should I munch on while coding?
 *
 * I learned that picking the right snack depends on so many things!
 * Am I debugging (need focus snacks) or just reviewing code (anything goes)?
 * Do I have time to prepare something or need instant fuel?
 *
 * Prof. Teeters reminded me: "The best snack is one that doesn't
 * get crumbs in your keyboard." That really stuck with me! 🟠
 */

const data = {
  domain: "Coding Snacks",
  description: "Find the perfect snack for your coding session based on mood, time, and health goals",
  options: [
    {
      name: "Trail Mix",
      category: "nuts",
      mood: "focused",
      prepMinutes: 0,
      messLevel: 1,
      isHealthy: true,
    },
    {
      name: "Apple Slices with Peanut Butter",
      category: "fruit",
      mood: "energized",
      prepMinutes: 3,
      messLevel: 2,
      isHealthy: true,
    },
    {
      name: "Cheese and Crackers",
      category: "dairy",
      mood: "relaxed",
      prepMinutes: 2,
      messLevel: 2,
      isHealthy: false,
    },
    {
      name: "Dark Chocolate Squares",
      category: "sweet",
      mood: "focused",
      prepMinutes: 0,
      messLevel: 1,
      isHealthy: true,
    },
    {
      name: "Baby Carrots",
      category: "vegetable",
      mood: "focused",
      prepMinutes: 0,
      messLevel: 1,
      isHealthy: true,
    },
    {
      name: "Popcorn",
      category: "grain",
      mood: "relaxed",
      prepMinutes: 3,
      messLevel: 3,
      isHealthy: true,
    },
    {
      name: "Greek Yogurt with Berries",
      category: "dairy",
      mood: "energized",
      prepMinutes: 2,
      messLevel: 2,
      isHealthy: true,
    },
    {
      name: "Pretzel Sticks",
      category: "grain",
      mood: "relaxed",
      prepMinutes: 0,
      messLevel: 1,
      isHealthy: false,
    },
    {
      name: "Hummus with Veggie Sticks",
      category: "vegetable",
      mood: "focused",
      prepMinutes: 3,
      messLevel: 2,
      isHealthy: true,
    },
    {
      name: "String Cheese",
      category: "dairy",
      mood: "relaxed",
      prepMinutes: 0,
      messLevel: 1,
      isHealthy: true,
    },
    {
      name: "Banana",
      category: "fruit",
      mood: "energized",
      prepMinutes: 0,
      messLevel: 1,
      isHealthy: true,
    },
    {
      name: "Rice Cakes with Almond Butter",
      category: "grain",
      mood: "focused",
      prepMinutes: 2,
      messLevel: 2,
      isHealthy: true,
    },
    {
      name: "Gummy Bears",
      category: "sweet",
      mood: "relaxed",
      prepMinutes: 0,
      messLevel: 1,
      isHealthy: false,
    },
    {
      name: "Edamame",
      category: "vegetable",
      mood: "focused",
      prepMinutes: 5,
      messLevel: 2,
      isHealthy: true,
    },
    {
      name: "Granola Bar",
      category: "grain",
      mood: "energized",
      prepMinutes: 0,
      messLevel: 1,
      isHealthy: true,
    },
    {
      name: "Chips and Salsa",
      category: "grain",
      mood: "relaxed",
      prepMinutes: 1,
      messLevel: 3,
      isHealthy: false,
    },
    {
      name: "Almonds",
      category: "nuts",
      mood: "focused",
      prepMinutes: 0,
      messLevel: 1,
      isHealthy: true,
    },
    {
      name: "Frozen Grapes",
      category: "fruit",
      mood: "relaxed",
      prepMinutes: 0,
      messLevel: 1,
      isHealthy: true,
    },
    // Added to fill coverage gaps - every mood + category combo now has options!
    {
      name: "Blueberries",
      category: "fruit",
      mood: "focused",
      prepMinutes: 0,
      messLevel: 1,
      isHealthy: true,
    },
    {
      name: "Celery Sticks",
      category: "vegetable",
      mood: "relaxed",
      prepMinutes: 0,
      messLevel: 1,
      isHealthy: true,
    },
    {
      name: "Cucumber Slices",
      category: "vegetable",
      mood: "energized",
      prepMinutes: 1,
      messLevel: 1,
      isHealthy: true,
    },
    {
      name: "Cottage Cheese",
      category: "dairy",
      mood: "focused",
      prepMinutes: 0,
      messLevel: 1,
      isHealthy: true,
    },
    {
      name: "Cashews",
      category: "nuts",
      mood: "relaxed",
      prepMinutes: 0,
      messLevel: 1,
      isHealthy: true,
    },
    {
      name: "Honey Roasted Peanuts",
      category: "nuts",
      mood: "energized",
      prepMinutes: 0,
      messLevel: 1,
      isHealthy: false,
    },
    {
      name: "Jelly Beans",
      category: "sweet",
      mood: "energized",
      prepMinutes: 0,
      messLevel: 1,
      isHealthy: false,
    },
  ],
};
